apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-n-deploy
  namespace: demo-secure-images
  labels:
    app.kubernetes.io/instance: pipeline-signed
    tekton.dev/pipeline: build-n-deploy
spec:
  params:
    - name: deployment-name
      value: ' pipelines-vote-api'
    - name: git-url
      value: 'https://github.com/openshift/pipelines-vote-api.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: >-
        quay-registry-quay-quay-registry.apps.cluster-66r2w.66r2w.sandbox1946.opentlc.com/ilago/demo-secure-images:v1
    - name: namespace
      value: demo-secure-images
  pipelineRef:
    name: build-n-deploy
  serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: source-pvc