apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acs-integrations
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: demo-secure-images
rules:
  - apiGroups:
      - "*"
    resources:
      - secrets
      - routes
    verbs:
      - get
      - watch
      - list
      - create
      - patch
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acs-gitops
  namespace: demo-secure-images
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: acs-integrations-rb
subjects:
  - kind: ServiceAccount
    name: acs-gitops
    namespace: demo-secure-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: acs-integrations
