apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-sign-n-deploy
  namespace: demo-secure-images
  labels:
    tekton.dev/pipeline: build-sign-n-deploy
spec:
  params:
    - name: deployment-name
      value: pipelines-vote-api
    - name: git-url
      value: 'https://github.com/Everything-is-Code/pipelines-vote-api.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: 'ChangeMe/quayadmin/demo-secure-images:v1'
    - name: namespace
      value: demo-secure-images
  pipelineRef:
    name: build-sign-n-deploy
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: source-pvc
