kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  name: pipeline
  namespace: demo-secure-images
secrets:
  - name: regcred
imagePullSecrets:
  - name: regcred