apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-n-sign-commit
  namespace: demo-secure-images
spec:
  params:
    - default: 'https://github.com/rcarrata/spring-petclinic'
      description: The application git repository
      name: SOURCE_GIT
      type: string
    - default: master
      description: The application git revision
      name: SOURCE_REVISION
      type: string
    - default: 'https://github.com/rcarrata/spring-petclinic-config'
      description: The application manifests git repository
      name: MANIFESTS_GIT
      type: string
    - description: Image to be build from the code
      name: IMAGE
      type: string      
    - default: latest
      description: The application image tag to build
      name: IMAGE_TAG
      type: string
    - default: demo-secure-images
      description: Namespace where the Tekton project is installed by the release
      name: NAMESPACE
      type: string
    - description: Name of the deployment to be patched
      name: DEPLOYMENT_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.SOURCE_GIT)
        - name: revision
          value: $(params.SOURCE_REVISION)
        - name: depth
          value: '0'
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: wait-application
      params:
        - name: application-name
          value: tetris
      runAfter:
        - git-update-deployment
      taskRef:
        kind: Task
        name: argocd-task-sync-and-wait
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: IMAGE_TAG
          value: $(params.IMAGE_TAG)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:3c2ea396a114221575a4031d90d28c43563f7b96288374e0ba8b22de3ed97b5a
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah-1-13-0-with-tag
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: sign-image
      params:
        - name: cosignkey
          value: cosign
        - name: image
          value: $(params.IMAGE)@$(tasks.build-image.results.IMAGE_DIGEST)
        - name: namespace
          value: $(params.NAMESPACE)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: cosign
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: rox-image-scan
      params:
        - name: rox_central_endpoint
          value: roxsecrets
        - name: rox_api_token
          value: roxsecrets
        - name: image
          value: $(params.IMAGE)
        - name: output_format
          value: pretty
        - name: image_digest
          value: $(tasks.build-image.results.IMAGE_DIGEST)
      runAfter:
        - sign-image
      taskRef:
        kind: ClusterTask
        name: rox-image-scan
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-update-deployment
      params:
        - name: GIT_REPOSITORY
          value: $(params.MANIFESTS_GIT)
        - name: GIT_USERNAME
          value: gogs
        - name: CURRENT_IMAGE
          value: 'quay.io/siamaksade/spring-petclinic:latest'
        - name: NEW_IMAGE
          value: $(params.IMAGE)
        - name: NEW_DIGEST
          value: $(tasks.build-image.results.IMAGE_DIGEST)
        - name: KUSTOMIZATION_PATH
          value: environments/dev
        - name: GIT_TOKEN
          value: gittoken
      runAfter:
        - rox-image-scan
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
