apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
- 00_namespace.yaml
- 01_source-pvc.yaml
- 02_service-account.yaml
- 03_pipeline_build-n-deploy.yaml
- 04_pipeline_build-sign-n-deploy.yaml
